global:
  scrape_interval: 15s  # Scrape every 15 seconds

scrape_configs:
  - job_name: 'otel-collector'
    static_configs:
      - targets: ['otel-collector:9464']

  - job_name: 'loki'
    static_configs:
      - targets: ['loki:3100']

  - job_name: 'greenhouse-app'
    static_configs:
      - targets: ['greenhouse-app:8000']